# Generated by Django 2.2 on 2019-05-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('background_task', '0002_auto_20170927_1109'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table=None,
        ),
    ]
